#!/usr/bin/env python3
"""Generate src/arts.js and CREDITS.md from arts/manifest.json + arts/<id>.txt.

Run after adding or editing an art:  python3 scripts/build_arts.py
"""
import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
ARTS = ROOT / "arts"
manifest = json.loads((ARTS / "manifest.json").read_text(encoding="utf-8"))

entries, credits = [], []
for m in manifest:
    path = ARTS / f"{m['id']}.txt"
    art = path.read_text(encoding="utf-8")
    art = "\n".join(l.rstrip() for l in art.split("\n")).strip("\n") + "\n"
    art = re.sub(r"\n{3,}", "\n\n", art)
    path.write_text(art, encoding="utf-8")  # normalize in place
    width = max(len(l) for l in art.split("\n"))
    if width > 90:
        raise SystemExit(f"{m['id']}: {width} cols wide; keep arts <= 90 so they fit GitHub comments")
    entries.append({**m, "art": art})
    credits.append(f"- **{m['name']}** (`{m['id']}`) — {m.get('credit', 'unknown')}")

js = (
    "// GENERATED by scripts/build_arts.py from arts/manifest.json + arts/*.txt. Do not edit by hand.\n"
    "// eslint-disable-next-line no-unused-vars\n"
    "const ASCII_APPROVE_BUNDLED = " + json.dumps(entries, ensure_ascii=False, indent=2) + ";\n"
)
(ROOT / "src" / "arts.js").write_text(js, encoding="utf-8")

(ROOT / "CREDITS.md").write_text(
    "# Credits\n\n"
    "ASCII art is folk art: most pieces below have circulated on Usenet and ASCII archives for decades. "
    "Artist signatures are kept inside the art wherever the original had them. "
    "If you are an artist listed here and want a piece removed or credited differently, open an issue.\n\n"
    "Text banners are rendered with [pyfiglet](https://github.com/pwaller/pyfiglet) fonts.\n\n"
    + "\n".join(credits) + "\n\n"
    "Sources: [asciiart.eu](https://www.asciiart.eu), [ascii.co.uk](https://ascii.co.uk), rec.arts.ascii / alt.ascii-art archives.\n",
    encoding="utf-8",
)
print(f"built {len(entries)} arts -> src/arts.js, CREDITS.md")
